window.wordCloudData = [
    { text: "Ultra Low Power", size: 40, category: "primary" },
    { text: "TPMS Prototype", size: 38, category: "primary" },
    { text: "Illini Solar Car", size: 30, category: "secondary" },
    { text: "AbbVie Research", size: 28, category: "secondary" },
    { text: "BLE Protocol", size: 28, category: "secondary" },
    { text: "Discrete Design", size: 26, category: "secondary" },
    { text: "EFR32BG22", size: 22, category: "tertiary" },
    { text: "MS5837 Barometer", size: 22, category: "tertiary" },
    { text: "ADXL362", size: 20, category: "tertiary" },
    { text: "FSM", size: 20, category: "tertiary" },
    { text: "CR1632 Coin Cell", size: 18, category: "tertiary" },
    { text: "Deep Sleep", size: 16, category: "quaternary" },
    { text: "Reverse Engineering", size: 16, category: "quaternary" },
    { text: "KiCad PCB", size: 14, category: "quaternary" },
    { text: "Hardware Design", size: 14, category: "quaternary" },
    { text: "Firmware", size: 24, category: "secondary" },
    { text: "Payload Encoding", size: 22, category: "tertiary" },
    { text: "CRC8", size: 18, category: "tertiary" },
    { text: "Carbon Fiber", size: 20, category: "tertiary" },
    { text: "Energy Research", size: 24, category: "secondary" },
    { text: "Vehicle Dynamics", size: 18, category: "tertiary" },
    { text: "Telemetry", size: 16, category: "quaternary" },
    { text: "Size Constraint", size: 16, category: "quaternary" },
    { text: "SWD Debugging", size: 18, category: "tertiary" },
    { text: "Micro-power", size: 14, category: "quaternary" },
    { text: "Embedded", size: 16, category: "quaternary" }
];
