window.wordCloudData = [
    { text: "Live Video System", size: 40, category: "primary" },
    { text: "Rocket Avionics", size: 38, category: "primary" },
    { text: "ESP32-P4", size: 30, category: "secondary" },
    { text: "Digital Compression", size: 28, category: "secondary" },
    { text: "JPEG Encoding", size: 28, category: "secondary" },
    { text: "Analog to Digital", size: 26, category: "secondary" },
    { text: "TVP5151", size: 22, category: "tertiary" },
    { text: "LR2021", size: 22, category: "tertiary" },
    { text: "FSK Transmission", size: 20, category: "tertiary" },
    { text: "434 MHz", size: 20, category: "tertiary" },
    { text: "Packet Fragmentation", size: 18, category: "tertiary" },
    { text: "Reed-Solomon", size: 16, category: "quaternary" },
    { text: "DVP Interface", size: 16, category: "quaternary" },
    { text: "YUV422", size: 14, category: "quaternary" },
    { text: "Hardware Encoder", size: 14, category: "quaternary" },
    { text: "Wireless Video", size: 24, category: "secondary" },
    { text: "PCB Design", size: 22, category: "tertiary" },
    { text: "KiCad", size: 18, category: "tertiary" },
    { text: "Firmware", size: 20, category: "tertiary" },
    { text: "Embedded Systems", size: 24, category: "secondary" },
    { text: "Real-time Processing", size: 18, category: "tertiary" },
    { text: "DMA Transfer", size: 16, category: "quaternary" },
    { text: "I2C Communication", size: 16, category: "quaternary" },
    { text: "Power Management", size: 18, category: "tertiary" },
    { text: "Buck Converter", size: 14, category: "quaternary" },
    { text: "GPS Integration", size: 16, category: "quaternary" },
    { text: "NTSC Video", size: 16, category: "quaternary" },
    { text: "Runcam Split 4", size: 14, category: "quaternary" },
    { text: "Error Correction", size: 18, category: "tertiary" },
    { text: "Video Pipeline", size: 20, category: "tertiary" },
    { text: "RF Design", size: 18, category: "tertiary" },
    { text: "Telemetry", size: 16, category: "quaternary" },
    { text: "Flight Computer", size: 18, category: "tertiary" },
    { text: "MIDAS", size: 14, category: "quaternary" },
    { text: "Sensor Suite", size: 16, category: "quaternary" }
];
